name = "blog"
main = "src/index.ts"
compatibility_date = "2025-01-31"

compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDkxZjIzMTAtZGUxYS00NTg0LWFhMDEtZmQyNWI3Yjc1NWMwIiwidGVuYW50X2lkIjoiNGI3ZGM0YzA1MWZmNjAyNjMwOWU5YTE0NGE2NTMwMDkzYmNlYmQ1M2Y3NzE0MjI5Y2I5OWI3MWUzMjBlZDgyZiIsImludGVybmFsX3NlY3JldCI6IjllOTUxOTBiLTFmMDYtNGVmOC04MGRlLWFiNjIzZjE1NTRlNSJ9.DAuzWqMBfXAgt93y9G5Tmdee8BfkRqvT5ChBRNDP0AM"
JWT_Secret = "passkey"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1